apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ASG07/kubernetes-demo-config.git
    targetRevision: HEAD
    path: k8s-simple
  destination:
    server: https://kubernetes.default.svc
    namespace: laravel

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true