apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      initContainers:
      - name: migration
        image: your-dockerhub-username/laravel-app:v2  # Change 'your-dockerhub-username' to your Docker Hub username
        command: ['php', 'artisan', 'migrate', '--force']
        envFrom:
        - configMapRef:
            name: laravel-config
        - secretRef:
            name: laravel-secret
      containers:
      - name: laravel
        image: your-dockerhub-username/laravel-app:v2  # Change 'your-dockerhub-username' to your Docker Hub username
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: laravel-config
        - secretRef:
            name: laravel-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: laravel
  namespace: laravel
spec:
  selector:
    app: laravel
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer  # Or ClusterIP if you have an ingress
