apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "laravel"
        - name: MYSQL_USER
          value: "laravel"
        - name: MYSQL_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        emptyDir: {}  # Simple storage - data will be lost on pod restart
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: laravel
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
