apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel
type: Opaque
data:
  APP_KEY: YmFzZTY0OlptUTYvdTdYY01Wd24rTzFDQ3Zkbytalz+GNtUSWlF7NDNny+U=  # Change this!
  DB_PASSWORD: cGFzc3dvcmQ=  # 'password' - change this!
