apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel
type: Opaque
data:
  APP_KEY: YmFzZTY0OmxTM05WUVE2VTlrdnBUazN2dGw5NXAwYThTRHl2aUFwUGZqKzFTOGFULzg9  # Generated valid key
  DB_PASSWORD: cGFzc3dvcmQ=  # 'password' - change this!
